export const negativeKeywords = [
    "abandoned", "abhorrent", "abrasive", "absent", "absurd", "abusive", "afraid", "aggravating", "aggressive", "agonizing",
    "aimless", "alarming", "alienated", "angry", "annoyed", "annoying", "antagonistic", "anxious", "apathetic", "appalling",
    "arduous", "argumentative", "arrogant", "ashamed", "assaultive", "astonished", "astounded", "atrocious", "awful", "awkward",
    "bad", "baffled", "barbaric", "barren", "baseless", "bashful", "battered", "belittled", "belligerent", "bereft",
    "betrayed", "bewildered", "bitter", "bizarre", "bleak", "blunder", "bothersome", "brash", "brutal", "burdensome",
    "callous", "cantankerous", "careless", "chaotic", "chilling", "clumsy", "coarse", "cold", "combative", "comfortless",
    "complacent", "complaint", "complicated", "conceited", "condemned", "conflicted", "confusing", "conniving", "contemptible", "contradictory",
    "contrived", "corrosive", "corrupt", "cowardly", "crass", "crazy", "creepy", "crime", "cruel", "cumbersome",
    "cynical", "damaged", "dangerous", "dislike", "dark", "dastardly", "daunting", "deadly", "debilitating", "deceitful", "deceptive",
    "defeated", "defective", "defenseless", "defiant", "deficient", "dejected", "delirious", "demeaning", "demoralized", "denounced",
    "dependent", "depressed", "deprived", "deranged", "derogatory", "desolate", "despair", "desperate", "destructive", "detached",
    "detestable", "detrimental", "devastated", "devious", "difficult", "diminished", "dirty", "disadvantaged", "disagreeable", "disappointed",
    "disappointing", "disastrous", "discarded", "discouraged", "discredited", "disdainful", "disgusted", "dishonest", "dishonorable", "disillusioned",
    "dislike", "disordered", "disorganized", "disoriented", "disparaging", "dispensable", "displeased", "disrespectful", "disruptive", "dissatisfied",
    "distasteful", "distorted", "distracted", "distraught", "distressed", "disturbed", "doubtful", "draconian", "dreadful", "dreary",
    "dubious", "dull", "dysfunctional", "eccentric", "eerie", "egotistical", "elusive", "embarrassed", "embittered", "embroiled",
    "emotionless", "empty", "enraged", "envious", "erasable", "erratic", "erroneous", "evasive", "evil", "exacerbated",
    "exasperating", "excessive", "excruciating", "exhausted", "exploitative", "explosive", "exposed", "failure", "faint", "faithless",
    "fake", "false", "faltering", "fanatical", "farcical", "fatal", "fatigued", "faulty", "fearful", "feeble",
    "fickle", "fiery", "filthy", "flawed", "foolish", "foolhardy", "forlorn", "forsaken", "foul", "fractious",
    "fragile", "frantic", "frazzled", "frenzied", "frightened", "frightful", "frivolous", "frustrated", "futile", "galling",
    "ghastly", "gloomy", "glum", "gory", "graceless", "grave", "greedy", "grim", "grisly", "grotesque",
    "grouchy", "gruesome", "grumpy", "guilty", "haggard", "harassed", "hard", "hard-hearted", "harmful", "harsh",
    "hasty", "hateful", "haughty", "hazardous", "hectic", "hedonistic", "helpless", "hesitant", "hideous", "hindrance",
    "hollow", "hopeless", "horrendous", "horrible", "horrific", "hostile", "humdrum", "humiliated", "hungry", "hurt",
    "hurtful", "hysterical", "ignoble", "ignorant", "ignored", "ill", "illegal", "illicit", "illusory", "imbalanced",
    "immaterial", "impatient", "imperfect", "impetuous", "impolite", "important", "impractical", "impulsive", "inadequate", "incoherent",
    "incompetent", "inconclusive", "inconsequential", "inconsiderate", "inconsistent", "indecisive", "indifferent", "indignant", "indulgent", "inept",
    "inferior", "infuriating", "inhibited", "inhumane", "inimical", "injurious", "insecure", "insensitive", "insignificant", "insipid",
    "insistent", "insolent", "instable", "insufferable", "insufficient", "insular", "insulting", "intense", "interfering", "intimidated",
    "intolerable", "intolerant", "intrusive", "invalid", "invasive", "irate", "irrational", "irrelevant", "irritable", "irritating", "jealous", "jarring", "jittery", "joyless",
    "judgmental", "jumbled", "jumpy", "kafkaesque", "klutzy", "knockabout", "knotty", "knavery", "kitsch", "killing", "kleptomaniac", "kowtowing", "kvetching", "lackluster", "lame", "languid", "languish", "lapsed", "lashing", "late", "laughable", "lavish", "lawless", "lazy",
    "leery", "lethal", "lethargic", "liable", "libelous", "lies", "limited", "listless", "loathsome", "lonely",
    "lopsided", "lost", "loud", "lousy", "loveless", "low", "ludicrous", "lurid", "lustful", "lying",
    "macabre", "mad", "maddening", "maladjusted", "malicious", "malignant", "manipulative", "marred", "mean", "meddlesome",
    "mediocre", "melancholic", "menacing", "mendacious", "merciless", "messy", "miffed", "militant", "mindless", "miserable",
    "misguided", "mistaken", "mistrustful", "moody", "morbid", "morose", "mournful", "muddled", "murky", "mysterious",
    "naive", "narcissistic", "nasty", "naughty", "nauseating", "negative", "neglected", "negligent", "nervous", "nettlesome",
    "neurotic", "nihilistic", "noisy", "nonchalant", "nonsensical", "noxious", "numb", "objectionable", "obscene", "obstinate",
    "obstructive", "odd", "offensive", "officious", "ominous", "oppressive", "outrageous", "overbearing", "overcritical", "overwhelmed",
    "painful", "panic", "paranoid", "passive", "pathetic", "peevish", "pernicious", "perplexed", "perverse", "petty",
    "phobic", "picky", "pitiable", "pitiful", "plagued", "pointless", "poisonous", "poor", "prejudiced", "presumptuous",
    "pretentious", "problematic", "prohibitive", "punitive", "puzzled", "quarrelsome", "questionable", "quixotic", "rage", "rancorous",
    "rash", "rebellious", "reckless", "reclusive", "remorseful", "repellent", "reprehensible", "repressed", "resentful", "restless",
    "ridiculous", "risky", "rotten", "rough", "rude", "ruined", "ruthless", "sad", "sarcastic", "sardonic",
    "scandalous", "sceptical", "scornful", "screaming", "severe", "shady", "shaky", "shallow", "shameful", "shattered",
    "shocking", "shoddy", "short-sighted", "shunned", "sick", "sickening", "sinister", "skeptical", "sloppy", "slow",
    "sluggish", "sly", "small-minded", "smothered", "snide", "sordid", "sorrowful", "sour", "spiteful", "stagnant",
    "startled", "stern", "stifled", "stingy", "stressed", "stricken", "strict", "struggling", "stubborn", "stuffy",
    "stunned", "stupid", "submissive", "subpar", "superficial", "superstitious", "suppressive", "suspicious", "tacky", "tainted",
    "tasteless", "tense", "terrible", "terrified", "tetchy", "thankless", "thorny", "thoughtless", "threatening", "tight",
    "tired", "tiresome", "tormented", "tortuous", "toxic", "tragic", "traumatic", "treacherous", "troubled", "troublesome",
    "truculent", "tumultuous", "turbulent", "ugly", "unappealing", "unappetizing", "unbalanced", "unbearable", "unbelievable", "uncaring",
    "uncomfortable", "unconcerned", "uncontrolled", "undependable", "underhanded", "undermined", "undesirable", "undisciplined", "uneasy", "unethical",
    "unfair", "unfavorable", "unfit", "unfocused", "unforgiving", "unfortunate", "ungrateful", "unhappy", "unhealthy", "unimpressive",
    "unjust", "unkind", "unlucky", "unpleasant", "unpopular", "unpredictable", "unprepared", "unproductive", "unprofitable", "unqualified",
    "unraveling", "unrealistic", "unreliable", "unresolved", "unresponsive", "unruly", "unsafe", "unsatisfactory", "unsavory", "unsettled",
    "unsophisticated", "unstable", "unsteady", "unsuccessful", "unsupported", "unsure", "untimely", "untouchable", "untrustworthy", "untruthful",
    "unwanted", "unwarranted", "unwelcoming", "unwieldy", "unwilling", "unwise", "upset", "useless", "vague", "vain",
    "vapid", "vengeful", "venomous", "vexing", "vicious", "vile", "vindictive", "violent", "volatile", "vulgar",
    "wary", "wasteful", "weak", "weary", "weird", "wicked", "wily", "woeful", "worn", "worried",
    "worse", "worst", "worthless", "wounded", "wrathful", "wretched", "wrong", "yielding", "zealous"]


