export const positiveKeywords = [
    "accomplished", "achievement", "active", "admirable", "adventure", "affectionate", "alert", "alive", "amazed", "amazing",
    "ambitious", "ample", "amused", "angel", "animated", "appreciate", "artistic", "astonishing", "astounding", "attentive",
    "attractive", "authentic", "awesome", "beaming", "beautiful", "believe", "beneficial", "bliss", "bountiful", "brave",
    "bright", "brilliant", "bubbly", "calm", "capable", "captivating", "carefree", "celebrated", "champion", "charismatic",
    "charming", "cheerful", "cherished", "chic", "clarity", "classic", "clever", "colorful", "committed", "compassionate",
    "confident", "conscientious", "considerate", "content", "convenient", "cool", "courageous", "courteous", "creative",
    "cuddly", "curious", "dazzling", "delicate", "delightful", "desirable", "determined", "diligent", "diplomatic", "divine",
    "dynamic", "eager", "easygoing", "ecstatic", "effective", "efficient", "elegant", "eloquent", "enchanting", "encouraging",
    "energetic", "engaged", "engaging", "enjoyable", "enthusiastic", "essential", "esteemed", "euphoric", "excellent", "exciting",
    "exhilarating", "exquisite", "extraordinary", "exuberant", "fabulous", "fair", "faithful", "famous", "fantastic", "favorable",
    "fearless", "feisty", "festive", "fine", 'fit', "flourishing", "fortunate", "free", "fresh", "friendly", "fun", "funny",
    "generous", "genius", "genuine", "gifted", "gleeful", "glorious", "golden", "good", "graceful", "gracious", "grateful",
    "great", "groovy", "groundbreaking", "growing", "guaranteed", "happy", "hardworking", "harmonious", "healed", "healthy",
    "heartfelt", "heartwarming", "heavenly", "helpful", "heroic", "hilarious", "honest", "honorable", "honored", "hopeful",
    "hospitable", "hot", "humble", "humorous", "ideal", "illuminating", "imaginative", "immaculate", "impartial", "important",
    "impressive", "incredible", "independent", "industrious", "innovative", "inspired", "inspiring", "intelligent", "intuitive",
    "inventive", "invincible", "joy", "joyful", "jubilant", "keen", "kind", "knowledgeable", "legendary", "light", "lively",
    "lovely", "loving", "loyal", "lucky", "luminous", "magical", "magnificent", "majestic", "marvelous", "masterful", "meaningful",
    "memorable", "merciful", "meritorious", "merry", "mesmerizing", "mindful", "miraculous", "motivated", "moving", "natural",
    "neat", "nice", "noble", "notable", "noteworthy", "nourishing", "nurturing", "optimal", "optimistic", "outstanding", "overjoyed",
    "passionate", "peaceful", "perfect", "persevering", "persistent", "playful", "pleasant", "pleased", "pleasing", "positive",
    "powerful", "prepared", "pretty", "pride", "principled", "productive", "progressive", "prosperous", "proud", "punctual",
    "purposeful", "radiant", "rapid", "rational", "ready", "realistic", "reassuring", "refined", "refreshing", "reliable",
    "remarkable", "resilient", "resolute", "resourceful", "respectful", "resplendent", "responsible", "responsive", "revered",
    "revolutionary", "rewarding", "rich", "righteous", "robust", "romantic", "safe", "satisfactory", "satisfied", "savvy",
    "scholarly", "scintillating", "seamless", "seasoned", "secure", "seductive", "selective", "self-reliant", "sensational",
    "sensible", "sensitive", "serene", "sharp", "shiny", "sincere", "skillful", "sleek", "smart", "smiling", "smooth",
    "snazzy", "sociable", "solid", "sophisticated", "sought-after", "spectacular", "spellbinding", "spontaneous", "spotless",
    "stable", "stellar", "stimulating", "striking", "strong", "stunning", "stupendous", "stylish", "suave", "sublime",
    "successful", "sufficient", "suitable", "sunny", "super", "superb", "supportive", "supreme", "surprising", "sustainable",
    "swanky", "sweet", "talented", "tantalizing", "tender", "terrific", "thankful", "thorough", "thoughtful", "thrilled",
    "thriving", "tidy", "timely", "top-notch", "tranquil", "trendy", "triumphant", "trusted", "trustworthy", "truthful",
    "unbelievable", "understanding", "unique", "unlimited", "unreal", "valiant", "valuable", "venerated", "vibrant", "victorious",
    "vigorous", "virtuous", "visionary", "vital", "vivacious", "vivid", "warm", "wealthy", "welcoming", "well", "wholesome",
    "willing", "wise", "witty", "wonderful", "wondrous", "worthy", "youthful", "zesty", "zippy"
]
